apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - https://github.com/cert-manager/cert-manager/releases/download/v1.18.2/cert-manager.crds.yaml
  - namespace.yaml

helmCharts:
- name: cert-manager
  repo: https://charts.jetstack.io
  releaseName: cert-manager
  namespace: cert-manager

- name: opentelemetry-collector
  repo: https://open-telemetry.github.io/opentelemetry-helm-charts
  releaseName: opentelemetry-collector
  namespace: observability
  valuesFile: values/otel.yaml

- name: prometheus
  repo: https://prometheus-community.github.io/helm-charts
  releaseName: prometheus
  namespace: observability
  valuesFile: values/prometheus.yaml

- name: loki
  repo: https://grafana.github.io/helm-charts
  releaseName: loki
  namespace: observability
  valuesFile: values/loki.yaml

- name: jaeger
  repo: https://jaegertracing.github.io/helm-charts
  releaseName: jaeger
  namespace: observability
  valuesFile: values/jaeger.yaml