apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: demo-nginx

resources:
  - namespace.yaml
  - telemetry.yaml
  - curly.yaml
  - deployment.yaml
  - waypoint.yaml
  - service.yaml
  - routes.yaml