apiVersion: v1
kind: Service
metadata:
  name: nginx
  labels:
    istio.io/use-waypoint: waypoint
    app: nginx
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
  type: ClusterIP