forceNamespace: "observability"

alertmanager:
  enabled: false

nodeExporter:
  enabled: false

prometheus-node-exporter:
  enabled: false

prometheus-pushgateway:
  enabled: false

server:
  retention: 3h
  extraArgs:
    web.enable-otlp-receiver: